/**
 * 汉字关卡字库（可练 300 字）
 *
 * 只收录声母+韵母落在课堂拼音字表内的常用字。
 * 描红字模数据来自 Hanzi Writer。
 */

export const GROUPS = [
  { id: "all", name: "全部" },
  { id: "nature", name: "自然" },
  { id: "body", name: "人物" },
  { id: "life", name: "生活" },
  { id: "animal", name: "动物" },
  { id: "school", name: "学习" },
];

const CHARACTERS_RAW = [
  // —— 学习 ——
  {
    id: "yi",
    char: "一",
    pinyin: "yī",
    group: "school",
    meaning: "数字一",
    strokeNames: [],
  },
  {
    id: "er",
    char: "二",
    pinyin: "èr",
    group: "school",
    meaning: "数字二",
    strokeNames: [],
  },
  {
    id: "san",
    char: "三",
    pinyin: "sān",
    group: "school",
    meaning: "数字三",
    strokeNames: [],
  },
  {
    id: "si",
    char: "四",
    pinyin: "sì",
    group: "school",
    meaning: "数字四",
    strokeNames: [],
  },
  {
    id: "wu",
    char: "五",
    pinyin: "wǔ",
    group: "school",
    meaning: "数字五",
    strokeNames: [],
  },
  {
    id: "liu",
    char: "六",
    pinyin: "liù",
    group: "school",
    meaning: "数字六",
    strokeNames: [],
  },
  {
    id: "qi",
    char: "七",
    pinyin: "qī",
    group: "school",
    meaning: "数字七",
    strokeNames: [],
  },
  {
    id: "ba",
    char: "八",
    pinyin: "bā",
    group: "school",
    meaning: "数字八",
    strokeNames: [],
  },
  {
    id: "jiu",
    char: "九",
    pinyin: "jiǔ",
    group: "school",
    meaning: "数字九",
    strokeNames: [],
  },
  {
    id: "shi",
    char: "十",
    pinyin: "shí",
    group: "school",
    meaning: "数字十",
    strokeNames: [],
  },
  {
    id: "bai",
    char: "百",
    pinyin: "bǎi",
    group: "school",
    meaning: "一百",
    strokeNames: [],
  },
  {
    id: "qian",
    char: "千",
    pinyin: "qiān",
    group: "school",
    meaning: "一千",
    strokeNames: [],
  },
  {
    id: "wan",
    char: "万",
    pinyin: "wàn",
    group: "school",
    meaning: "一万",
    strokeNames: [],
  },
  {
    id: "bu",
    char: "不",
    pinyin: "bù",
    group: "school",
    meaning: "不",
    strokeNames: [],
  },
  {
    id: "ye",
    char: "也",
    pinyin: "yě",
    group: "school",
    meaning: "也",
    strokeNames: [],
  },
  {
    id: "hen",
    char: "很",
    pinyin: "hěn",
    group: "school",
    meaning: "很",
    strokeNames: [],
  },
  {
    id: "zui",
    char: "最",
    pinyin: "zuì",
    group: "school",
    meaning: "最",
    strokeNames: [],
  },
  {
    id: "tai",
    char: "太",
    pinyin: "tài",
    group: "school",
    meaning: "太",
    strokeNames: [],
  },
  {
    id: "dou",
    char: "都",
    pinyin: "dōu",
    group: "school",
    meaning: "都",
    strokeNames: [],
  },
  {
    id: "jiu2",
    char: "就",
    pinyin: "jiù",
    group: "school",
    meaning: "就",
    strokeNames: [],
  },
  {
    id: "he",
    char: "和",
    pinyin: "hé",
    group: "school",
    meaning: "和",
    strokeNames: [],
  },
  {
    id: "shi2",
    char: "是",
    pinyin: "shì",
    group: "school",
    meaning: "是",
    strokeNames: [],
  },
  {
    id: "you",
    char: "有",
    pinyin: "yǒu",
    group: "school",
    meaning: "有",
    strokeNames: [],
  },
  {
    id: "mei",
    char: "没",
    pinyin: "méi",
    group: "school",
    meaning: "没有",
    strokeNames: [],
  },
  {
    id: "zai",
    char: "在",
    pinyin: "zài",
    group: "school",
    meaning: "在",
    strokeNames: [],
  },
  {
    id: "zhe2",
    char: "这",
    pinyin: "zhè",
    group: "school",
    meaning: "这",
    strokeNames: [],
  },
  {
    id: "na",
    char: "那",
    pinyin: "nà",
    group: "school",
    meaning: "那",
    strokeNames: [],
  },
  {
    id: "shen",
    char: "什",
    pinyin: "shén",
    group: "school",
    meaning: "什么",
    strokeNames: [],
  },
  {
    id: "shui",
    char: "谁",
    pinyin: "shuí",
    group: "school",
    meaning: "谁",
    strokeNames: [],
  },
  {
    id: "na2",
    char: "哪",
    pinyin: "nǎ",
    group: "school",
    meaning: "哪",
    strokeNames: [],
  },
  {
    id: "ji",
    char: "几",
    pinyin: "jǐ",
    group: "school",
    meaning: "几",
    strokeNames: [],
  },
  {
    id: "zen",
    char: "怎",
    pinyin: "zěn",
    group: "school",
    meaning: "怎么",
    strokeNames: [],
  },
  {
    id: "wei",
    char: "为",
    pinyin: "wèi",
    group: "school",
    meaning: "为",
    strokeNames: [],
  },
  {
    id: "neng",
    char: "能",
    pinyin: "néng",
    group: "school",
    meaning: "能",
    strokeNames: [],
  },
  {
    id: "hui",
    char: "会",
    pinyin: "huì",
    group: "school",
    meaning: "会",
    strokeNames: [],
  },
  {
    id: "ke",
    char: "可",
    pinyin: "kě",
    group: "school",
    meaning: "可以",
    strokeNames: [],
  },
  {
    id: "yao",
    char: "要",
    pinyin: "yào",
    group: "school",
    meaning: "要",
    strokeNames: [],
  },
  {
    id: "zhi",
    char: "知",
    pinyin: "zhī",
    group: "school",
    meaning: "知道",
    strokeNames: [],
  },
  {
    id: "dao",
    char: "道",
    pinyin: "dào",
    group: "school",
    meaning: "道理",
    strokeNames: [],
  },
  {
    id: "shuo",
    char: "说",
    pinyin: "shuō",
    group: "school",
    meaning: "说",
    strokeNames: [],
  },
  {
    id: "hua",
    char: "话",
    pinyin: "huà",
    group: "school",
    meaning: "话",
    strokeNames: [],
  },
  {
    id: "xue",
    char: "学",
    pinyin: "xué",
    group: "school",
    meaning: "学",
    strokeNames: [],
  },
  {
    id: "xi",
    char: "习",
    pinyin: "xí",
    group: "school",
    meaning: "习",
    strokeNames: [],
  },
  // —— 人物 ——
  {
    id: "wo",
    char: "我",
    pinyin: "wǒ",
    group: "body",
    meaning: "我",
    strokeNames: [],
  },
  {
    id: "ni",
    char: "你",
    pinyin: "nǐ",
    group: "body",
    meaning: "你",
    strokeNames: [],
  },
  {
    id: "ta",
    char: "他",
    pinyin: "tā",
    group: "body",
    meaning: "他",
    strokeNames: [],
  },
  {
    id: "ta2",
    char: "她",
    pinyin: "tā",
    group: "body",
    meaning: "她",
    strokeNames: [],
  },
  {
    id: "ren",
    char: "人",
    pinyin: "rén",
    group: "body",
    meaning: "人",
    strokeNames: ["撇", "捺"],
  },
  {
    id: "da",
    char: "大",
    pinyin: "dà",
    group: "body",
    meaning: "大",
    strokeNames: ["横", "撇", "捺"],
  },
  {
    id: "xiao",
    char: "小",
    pinyin: "xiǎo",
    group: "body",
    meaning: "小",
    strokeNames: ["竖钩", "撇", "点"],
  },
  {
    id: "kou",
    char: "口",
    pinyin: "kǒu",
    group: "body",
    meaning: "口",
    strokeNames: ["竖", "横折", "横"],
  },
  {
    id: "mu",
    char: "目",
    pinyin: "mù",
    group: "body",
    meaning: "眼睛",
    strokeNames: ["竖", "横折", "横", "横", "横"],
  },
  {
    id: "shou",
    char: "手",
    pinyin: "shǒu",
    group: "body",
    meaning: "手",
    strokeNames: ["撇", "横", "横", "竖钩"],
  },
  {
    id: "zu",
    char: "足",
    pinyin: "zú",
    group: "body",
    meaning: "脚",
    strokeNames: ["竖", "横折", "横", "竖", "横", "撇", "捺"],
  },
  {
    id: "xin",
    char: "心",
    pinyin: "xīn",
    group: "body",
    meaning: "心",
    strokeNames: ["点", "斜钩", "点", "点"],
  },
  {
    id: "er2",
    char: "耳",
    pinyin: "ěr",
    group: "body",
    meaning: "耳朵",
    strokeNames: ["横", "竖", "竖", "横", "横", "横"],
  },
  {
    id: "tou",
    char: "头",
    pinyin: "tóu",
    group: "body",
    meaning: "头",
    strokeNames: [],
  },
  {
    id: "mian",
    char: "面",
    pinyin: "miàn",
    group: "body",
    meaning: "脸",
    strokeNames: [],
  },
  {
    id: "ya",
    char: "牙",
    pinyin: "yá",
    group: "body",
    meaning: "牙",
    strokeNames: [],
  },
  {
    id: "fa",
    char: "发",
    pinyin: "fà",
    group: "body",
    meaning: "头发",
    strokeNames: [],
  },
  {
    id: "shen2",
    char: "身",
    pinyin: "shēn",
    group: "body",
    meaning: "身体",
    strokeNames: [],
  },
  {
    id: "nan",
    char: "男",
    pinyin: "nán",
    group: "body",
    meaning: "男",
    strokeNames: [],
  },
  {
    id: "nv",
    char: "女",
    pinyin: "nǚ",
    group: "body",
    meaning: "女",
    strokeNames: ["撇点", "撇", "横"],
  },
  {
    id: "zi",
    char: "子",
    pinyin: "zǐ",
    group: "body",
    meaning: "孩子",
    strokeNames: ["横撇", "竖钩", "横"],
  },
  {
    id: "fu",
    char: "父",
    pinyin: "fù",
    group: "body",
    meaning: "父亲",
    strokeNames: [],
  },
  {
    id: "mu2",
    char: "母",
    pinyin: "mǔ",
    group: "body",
    meaning: "母亲",
    strokeNames: [],
  },
  {
    id: "ba2",
    char: "爸",
    pinyin: "bà",
    group: "body",
    meaning: "爸爸",
    strokeNames: [],
  },
  {
    id: "ma2",
    char: "妈",
    pinyin: "mā",
    group: "body",
    meaning: "妈妈",
    strokeNames: [],
  },
  {
    id: "ge",
    char: "哥",
    pinyin: "gē",
    group: "body",
    meaning: "哥哥",
    strokeNames: [],
  },
  {
    id: "jie",
    char: "姐",
    pinyin: "jiě",
    group: "body",
    meaning: "姐姐",
    strokeNames: [],
  },
  {
    id: "di",
    char: "弟",
    pinyin: "dì",
    group: "body",
    meaning: "弟弟",
    strokeNames: [],
  },
  {
    id: "mei2",
    char: "妹",
    pinyin: "mèi",
    group: "body",
    meaning: "妹妹",
    strokeNames: [],
  },
  {
    id: "ye2",
    char: "爷",
    pinyin: "yé",
    group: "body",
    meaning: "爷爷",
    strokeNames: [],
  },
  {
    id: "nai",
    char: "奶",
    pinyin: "nǎi",
    group: "body",
    meaning: "奶奶",
    strokeNames: [],
  },
  {
    id: "hai",
    char: "孩",
    pinyin: "hái",
    group: "body",
    meaning: "孩子",
    strokeNames: [],
  },
  {
    id: "you2",
    char: "友",
    pinyin: "yǒu",
    group: "body",
    meaning: "朋友",
    strokeNames: [],
  },
  {
    id: "lao",
    char: "老",
    pinyin: "lǎo",
    group: "body",
    meaning: "老",
    strokeNames: [],
  },
  {
    id: "shao",
    char: "少",
    pinyin: "shǎo",
    group: "body",
    meaning: "少",
    strokeNames: [],
  },
  {
    id: "hao",
    char: "好",
    pinyin: "hǎo",
    group: "body",
    meaning: "好",
    strokeNames: [],
  },
  {
    id: "ai",
    char: "爱",
    pinyin: "ài",
    group: "body",
    meaning: "爱",
    strokeNames: [],
  },
  {
    id: "xi2",
    char: "喜",
    pinyin: "xǐ",
    group: "body",
    meaning: "喜欢",
    strokeNames: [],
  },
  {
    id: "huan",
    char: "欢",
    pinyin: "huān",
    group: "body",
    meaning: "欢乐",
    strokeNames: [],
  },
  // —— 生活 ——
  {
    id: "shang",
    char: "上",
    pinyin: "shàng",
    group: "life",
    meaning: "上面",
    strokeNames: ["竖", "横", "横"],
  },
  {
    id: "xia",
    char: "下",
    pinyin: "xià",
    group: "life",
    meaning: "下面",
    strokeNames: ["横", "竖", "点"],
  },
  {
    id: "zhong",
    char: "中",
    pinyin: "zhōng",
    group: "life",
    meaning: "中间",
    strokeNames: ["竖", "横折", "横", "竖"],
  },
  {
    id: "zuo",
    char: "左",
    pinyin: "zuǒ",
    group: "life",
    meaning: "左边",
    strokeNames: [],
  },
  {
    id: "you3",
    char: "右",
    pinyin: "yòu",
    group: "life",
    meaning: "右边",
    strokeNames: [],
  },
  {
    id: "qian2",
    char: "前",
    pinyin: "qián",
    group: "life",
    meaning: "前面",
    strokeNames: [],
  },
  {
    id: "hou",
    char: "后",
    pinyin: "hòu",
    group: "life",
    meaning: "后面",
    strokeNames: [],
  },
  {
    id: "li",
    char: "里",
    pinyin: "lǐ",
    group: "life",
    meaning: "里面",
    strokeNames: [],
  },
  {
    id: "wai",
    char: "外",
    pinyin: "wài",
    group: "life",
    meaning: "外面",
    strokeNames: [],
  },
  {
    id: "dong",
    char: "东",
    pinyin: "dōng",
    group: "life",
    meaning: "东方",
    strokeNames: [],
  },
  {
    id: "nan2",
    char: "南",
    pinyin: "nán",
    group: "life",
    meaning: "南方",
    strokeNames: [],
  },
  {
    id: "xi3",
    char: "西",
    pinyin: "xī",
    group: "life",
    meaning: "西方",
    strokeNames: [],
  },
  {
    id: "bei",
    char: "北",
    pinyin: "běi",
    group: "life",
    meaning: "北方",
    strokeNames: [],
  },
  {
    id: "lai",
    char: "来",
    pinyin: "lái",
    group: "life",
    meaning: "来",
    strokeNames: [],
  },
  {
    id: "qu",
    char: "去",
    pinyin: "qù",
    group: "life",
    meaning: "去",
    strokeNames: [],
  },
  {
    id: "hui2",
    char: "回",
    pinyin: "huí",
    group: "life",
    meaning: "回",
    strokeNames: [],
  },
  {
    id: "chu",
    char: "出",
    pinyin: "chū",
    group: "life",
    meaning: "出",
    strokeNames: [],
  },
  {
    id: "jin",
    char: "进",
    pinyin: "jìn",
    group: "life",
    meaning: "进",
    strokeNames: [],
  },
  {
    id: "dao2",
    char: "到",
    pinyin: "dào",
    group: "life",
    meaning: "到",
    strokeNames: [],
  },
  {
    id: "kan",
    char: "看",
    pinyin: "kàn",
    group: "life",
    meaning: "看",
    strokeNames: [],
  },
  {
    id: "ting",
    char: "听",
    pinyin: "tīng",
    group: "life",
    meaning: "听",
    strokeNames: [],
  },
  {
    id: "chi",
    char: "吃",
    pinyin: "chī",
    group: "life",
    meaning: "吃",
    strokeNames: [],
  },
  {
    id: "he2",
    char: "喝",
    pinyin: "hē",
    group: "life",
    meaning: "喝",
    strokeNames: [],
  },
  {
    id: "shui2",
    char: "睡",
    pinyin: "shuì",
    group: "life",
    meaning: "睡",
    strokeNames: [],
  },
  {
    id: "zou",
    char: "走",
    pinyin: "zǒu",
    group: "life",
    meaning: "走",
    strokeNames: [],
  },
  {
    id: "pao",
    char: "跑",
    pinyin: "pǎo",
    group: "life",
    meaning: "跑",
    strokeNames: [],
  },
  {
    id: "zuo2",
    char: "坐",
    pinyin: "zuò",
    group: "life",
    meaning: "坐",
    strokeNames: [],
  },
  {
    id: "zhan",
    char: "站",
    pinyin: "zhàn",
    group: "life",
    meaning: "站",
    strokeNames: [],
  },
  {
    id: "fei",
    char: "飞",
    pinyin: "fēi",
    group: "life",
    meaning: "飞",
    strokeNames: [],
  },
  {
    id: "wan2",
    char: "玩",
    pinyin: "wán",
    group: "life",
    meaning: "玩",
    strokeNames: [],
  },
  {
    id: "mai",
    char: "买",
    pinyin: "mǎi",
    group: "life",
    meaning: "买",
    strokeNames: [],
  },
  {
    id: "gei",
    char: "给",
    pinyin: "gěi",
    group: "life",
    meaning: "给",
    strokeNames: [],
  },
  {
    id: "yong",
    char: "用",
    pinyin: "yòng",
    group: "life",
    meaning: "用",
    strokeNames: [],
  },
  {
    id: "zuo3",
    char: "做",
    pinyin: "zuò",
    group: "life",
    meaning: "做",
    strokeNames: [],
  },
  {
    id: "da2",
    char: "打",
    pinyin: "dǎ",
    group: "life",
    meaning: "打",
    strokeNames: [],
  },
  {
    id: "zhao",
    char: "找",
    pinyin: "zhǎo",
    group: "life",
    meaning: "找",
    strokeNames: [],
  },
  {
    id: "na3",
    char: "拿",
    pinyin: "ná",
    group: "life",
    meaning: "拿",
    strokeNames: [],
  },
  {
    id: "fang",
    char: "放",
    pinyin: "fàng",
    group: "life",
    meaning: "放",
    strokeNames: [],
  },
  {
    id: "kai",
    char: "开",
    pinyin: "kāi",
    group: "life",
    meaning: "开",
    strokeNames: ["横", "横", "撇", "竖"],
  },
  {
    id: "guan",
    char: "关",
    pinyin: "guān",
    group: "life",
    meaning: "关",
    strokeNames: [],
  },
  {
    id: "men2",
    char: "门",
    pinyin: "mén",
    group: "life",
    meaning: "门",
    strokeNames: ["点", "竖", "横折钩"],
  },
  {
    id: "jia",
    char: "家",
    pinyin: "jiā",
    group: "life",
    meaning: "家",
    strokeNames: [],
  },
  {
    id: "fang2",
    char: "房",
    pinyin: "fáng",
    group: "life",
    meaning: "房",
    strokeNames: [],
  },
  {
    id: "che",
    char: "车",
    pinyin: "chē",
    group: "life",
    meaning: "车",
    strokeNames: ["横", "撇折", "横", "竖"],
  },
  {
    id: "lu",
    char: "路",
    pinyin: "lù",
    group: "life",
    meaning: "路",
    strokeNames: [],
  },
  {
    id: "shu",
    char: "书",
    pinyin: "shū",
    group: "life",
    meaning: "书",
    strokeNames: [],
  },
  {
    id: "yi2",
    char: "衣",
    pinyin: "yī",
    group: "life",
    meaning: "衣服",
    strokeNames: [],
  },
  {
    id: "fan",
    char: "饭",
    pinyin: "fàn",
    group: "life",
    meaning: "饭",
    strokeNames: [],
  },
  {
    id: "cai",
    char: "菜",
    pinyin: "cài",
    group: "life",
    meaning: "菜",
    strokeNames: [],
  },
  {
    id: "shui3",
    char: "水",
    pinyin: "shuǐ",
    group: "life",
    meaning: "水",
    strokeNames: ["竖钩", "横撇", "撇", "捺"],
  },
  // —— 自然 ——
  {
    id: "ri",
    char: "日",
    pinyin: "rì",
    group: "nature",
    meaning: "太阳 · 日子",
    strokeNames: ["竖", "横折", "横", "横"],
  },
  {
    id: "yue",
    char: "月",
    pinyin: "yuè",
    group: "nature",
    meaning: "月亮",
    strokeNames: ["撇", "横折钩", "横", "横"],
  },
  {
    id: "shan",
    char: "山",
    pinyin: "shān",
    group: "nature",
    meaning: "山",
    strokeNames: ["竖", "竖折", "竖"],
  },
  {
    id: "huo",
    char: "火",
    pinyin: "huǒ",
    group: "nature",
    meaning: "火",
    strokeNames: ["点", "撇", "撇", "捺"],
  },
  {
    id: "mu3",
    char: "木",
    pinyin: "mù",
    group: "nature",
    meaning: "木",
    strokeNames: ["横", "竖", "撇", "捺"],
  },
  {
    id: "tu",
    char: "土",
    pinyin: "tǔ",
    group: "nature",
    meaning: "土",
    strokeNames: ["横", "竖", "横"],
  },
  {
    id: "shi3",
    char: "石",
    pinyin: "shí",
    group: "nature",
    meaning: "石",
    strokeNames: ["横", "撇", "竖", "横折", "横"],
  },
  {
    id: "tian",
    char: "田",
    pinyin: "tián",
    group: "nature",
    meaning: "田",
    strokeNames: ["竖", "横折", "横", "竖", "横"],
  },
  {
    id: "tian2",
    char: "天",
    pinyin: "tiān",
    group: "nature",
    meaning: "天",
    strokeNames: ["横", "横", "撇", "捺"],
  },
  {
    id: "yu",
    char: "雨",
    pinyin: "yǔ",
    group: "nature",
    meaning: "雨",
    strokeNames: ["横", "竖", "横折钩", "点", "点", "点", "点", "点"],
  },
  {
    id: "yun",
    char: "云",
    pinyin: "yún",
    group: "nature",
    meaning: "云",
    strokeNames: ["横", "横", "撇折", "点"],
  },
  {
    id: "feng",
    char: "风",
    pinyin: "fēng",
    group: "nature",
    meaning: "风",
    strokeNames: ["撇", "横折弯钩", "撇", "点"],
  },
  {
    id: "dian",
    char: "电",
    pinyin: "diàn",
    group: "nature",
    meaning: "电",
    strokeNames: ["竖", "横折", "横", "竖", "竖弯钩"],
  },
  {
    id: "xing",
    char: "星",
    pinyin: "xīng",
    group: "nature",
    meaning: "星",
    strokeNames: ["竖", "横折", "横", "横", "撇", "横", "横", "竖", "横"],
  },
  {
    id: "xue2",
    char: "雪",
    pinyin: "xuě",
    group: "nature",
    meaning: "雪",
    strokeNames: [],
  },
  {
    id: "hua2",
    char: "花",
    pinyin: "huā",
    group: "nature",
    meaning: "花",
    strokeNames: ["横", "竖", "竖", "撇", "竖弯钩", "撇", "竖弯钩"],
  },
  {
    id: "cao",
    char: "草",
    pinyin: "cǎo",
    group: "nature",
    meaning: "草",
    strokeNames: ["横", "竖", "竖", "竖", "横折", "横", "横", "横", "竖"],
  },
  {
    id: "shu2",
    char: "树",
    pinyin: "shù",
    group: "nature",
    meaning: "树",
    strokeNames: [],
  },
  {
    id: "ye3",
    char: "叶",
    pinyin: "yè",
    group: "nature",
    meaning: "叶",
    strokeNames: [],
  },
  {
    id: "guo2",
    char: "果",
    pinyin: "guǒ",
    group: "nature",
    meaning: "果",
    strokeNames: ["竖", "横折", "横", "横", "横", "竖", "撇", "捺"],
  },
  {
    id: "chun",
    char: "春",
    pinyin: "chūn",
    group: "nature",
    meaning: "春",
    strokeNames: ["横", "横", "横", "撇", "捺", "竖", "横折", "横", "横"],
  },
  {
    id: "xia2",
    char: "夏",
    pinyin: "xià",
    group: "nature",
    meaning: "夏",
    strokeNames: [],
  },
  {
    id: "qiu",
    char: "秋",
    pinyin: "qiū",
    group: "nature",
    meaning: "秋",
    strokeNames: [],
  },
  {
    id: "dong2",
    char: "冬",
    pinyin: "dōng",
    group: "nature",
    meaning: "冬",
    strokeNames: [],
  },
  {
    id: "jiang",
    char: "江",
    pinyin: "jiāng",
    group: "nature",
    meaning: "江",
    strokeNames: [],
  },
  {
    id: "he3",
    char: "河",
    pinyin: "hé",
    group: "nature",
    meaning: "河",
    strokeNames: [],
  },
  {
    id: "hai2",
    char: "海",
    pinyin: "hǎi",
    group: "nature",
    meaning: "海",
    strokeNames: [],
  },
  {
    id: "guang",
    char: "光",
    pinyin: "guāng",
    group: "nature",
    meaning: "光",
    strokeNames: [],
  },
  {
    id: "ming",
    char: "明",
    pinyin: "míng",
    group: "nature",
    meaning: "明",
    strokeNames: ["竖", "横折", "横", "横", "撇", "横折钩", "横", "横"],
  },
  {
    id: "kong",
    char: "空",
    pinyin: "kōng",
    group: "nature",
    meaning: "空",
    strokeNames: [],
  },
  {
    id: "di2",
    char: "地",
    pinyin: "dì",
    group: "nature",
    meaning: "地",
    strokeNames: [],
  },
  {
    id: "qi2",
    char: "气",
    pinyin: "qì",
    group: "nature",
    meaning: "气",
    strokeNames: [],
  },
  {
    id: "yang",
    char: "阳",
    pinyin: "yáng",
    group: "nature",
    meaning: "阳",
    strokeNames: [],
  },
  {
    id: "hong",
    char: "红",
    pinyin: "hóng",
    group: "nature",
    meaning: "红",
    strokeNames: [],
  },
  {
    id: "huang",
    char: "黄",
    pinyin: "huáng",
    group: "nature",
    meaning: "黄",
    strokeNames: [],
  },
  {
    id: "lan",
    char: "蓝",
    pinyin: "lán",
    group: "nature",
    meaning: "蓝",
    strokeNames: [],
  },
  {
    id: "lv",
    char: "绿",
    pinyin: "lǜ",
    group: "nature",
    meaning: "绿",
    strokeNames: [],
  },
  {
    id: "bai2",
    char: "白",
    pinyin: "bái",
    group: "nature",
    meaning: "白",
    strokeNames: [],
  },
  {
    id: "hei",
    char: "黑",
    pinyin: "hēi",
    group: "nature",
    meaning: "黑",
    strokeNames: [],
  },
  {
    id: "jin2",
    char: "金",
    pinyin: "jīn",
    group: "nature",
    meaning: "金",
    strokeNames: [],
  },
  // —— 动物 ——
  {
    id: "yu2",
    char: "鱼",
    pinyin: "yú",
    group: "animal",
    meaning: "鱼",
    strokeNames: [],
  },
  {
    id: "niao",
    char: "鸟",
    pinyin: "niǎo",
    group: "animal",
    meaning: "鸟",
    strokeNames: [],
  },
  {
    id: "ma3",
    char: "马",
    pinyin: "mǎ",
    group: "animal",
    meaning: "马",
    strokeNames: [],
  },
  {
    id: "niu",
    char: "牛",
    pinyin: "niú",
    group: "animal",
    meaning: "牛",
    strokeNames: [],
  },
  {
    id: "yang2",
    char: "羊",
    pinyin: "yáng",
    group: "animal",
    meaning: "羊",
    strokeNames: [],
  },
  {
    id: "gou",
    char: "狗",
    pinyin: "gǒu",
    group: "animal",
    meaning: "狗",
    strokeNames: [],
  },
  {
    id: "mao",
    char: "猫",
    pinyin: "māo",
    group: "animal",
    meaning: "猫",
    strokeNames: [],
  },
  {
    id: "chong",
    char: "虫",
    pinyin: "chóng",
    group: "animal",
    meaning: "虫",
    strokeNames: [],
  },
  {
    id: "ji2",
    char: "鸡",
    pinyin: "jī",
    group: "animal",
    meaning: "鸡",
    strokeNames: [],
  },
  {
    id: "ya2",
    char: "鸭",
    pinyin: "yā",
    group: "animal",
    meaning: "鸭",
    strokeNames: [],
  },
  {
    id: "zhu",
    char: "猪",
    pinyin: "zhū",
    group: "animal",
    meaning: "猪",
    strokeNames: [],
  },
  {
    id: "tu2",
    char: "兔",
    pinyin: "tù",
    group: "animal",
    meaning: "兔",
    strokeNames: [],
  },
  {
    id: "hu",
    char: "虎",
    pinyin: "hǔ",
    group: "animal",
    meaning: "虎",
    strokeNames: [],
  },
  {
    id: "long",
    char: "龙",
    pinyin: "lóng",
    group: "animal",
    meaning: "龙",
    strokeNames: [],
  },
  {
    id: "she",
    char: "蛇",
    pinyin: "shé",
    group: "animal",
    meaning: "蛇",
    strokeNames: [],
  },
  {
    id: "hou2",
    char: "猴",
    pinyin: "hóu",
    group: "animal",
    meaning: "猴",
    strokeNames: [],
  },
  {
    id: "xiong",
    char: "熊",
    pinyin: "xióng",
    group: "animal",
    meaning: "熊",
    strokeNames: [],
  },
  {
    id: "xiang",
    char: "象",
    pinyin: "xiàng",
    group: "animal",
    meaning: "象",
    strokeNames: [],
  },
  {
    id: "shu3",
    char: "鼠",
    pinyin: "shǔ",
    group: "animal",
    meaning: "鼠",
    strokeNames: [],
  },
  {
    id: "wa",
    char: "蛙",
    pinyin: "wā",
    group: "animal",
    meaning: "蛙",
    strokeNames: [],
  },
  // —— 增补 ——
  {
    id: "zi2",
    char: "字",
    pinyin: "zì",
    group: "school",
    meaning: "汉字",
    strokeNames: [],
  },
  {
    id: "wen",
    char: "文",
    pinyin: "wén",
    group: "school",
    meaning: "文字",
    strokeNames: [],
  },
  {
    id: "zheng",
    char: "正",
    pinyin: "zhèng",
    group: "school",
    meaning: "正确",
    strokeNames: [],
  },
  {
    id: "ci",
    char: "词",
    pinyin: "cí",
    group: "school",
    meaning: "词语",
    strokeNames: [],
  },
  {
    id: "ju",
    char: "句",
    pinyin: "jù",
    group: "school",
    meaning: "句子",
    strokeNames: [],
  },
  {
    id: "ke2",
    char: "课",
    pinyin: "kè",
    group: "school",
    meaning: "上课",
    strokeNames: [],
  },
  {
    id: "ben",
    char: "本",
    pinyin: "běn",
    group: "school",
    meaning: "本子",
    strokeNames: [],
  },
  {
    id: "bi",
    char: "笔",
    pinyin: "bǐ",
    group: "school",
    meaning: "毛笔",
    strokeNames: [],
  },
  {
    id: "zhi2",
    char: "纸",
    pinyin: "zhǐ",
    group: "school",
    meaning: "纸张",
    strokeNames: [],
  },
  {
    id: "xie",
    char: "写",
    pinyin: "xiě",
    group: "school",
    meaning: "写字",
    strokeNames: [],
  },
  {
    id: "du",
    char: "读",
    pinyin: "dú",
    group: "school",
    meaning: "读书",
    strokeNames: [],
  },
  {
    id: "ren2",
    char: "认",
    pinyin: "rèn",
    group: "school",
    meaning: "认识",
    strokeNames: [],
  },
  {
    id: "shi4",
    char: "诗",
    pinyin: "shī",
    group: "school",
    meaning: "诗歌",
    strokeNames: [],
  },
  {
    id: "ge2",
    char: "歌",
    pinyin: "gē",
    group: "school",
    meaning: "唱歌",
    strokeNames: [],
  },
  {
    id: "shu4",
    char: "数",
    pinyin: "shù",
    group: "school",
    meaning: "数字",
    strokeNames: [],
  },
  {
    id: "wen2",
    char: "问",
    pinyin: "wèn",
    group: "school",
    meaning: "提问",
    strokeNames: [],
  },
  {
    id: "da3",
    char: "答",
    pinyin: "dá",
    group: "school",
    meaning: "回答",
    strokeNames: [],
  },
  {
    id: "ti",
    char: "题",
    pinyin: "tí",
    group: "school",
    meaning: "题目",
    strokeNames: [],
  },
  {
    id: "kao",
    char: "考",
    pinyin: "kǎo",
    group: "school",
    meaning: "考试",
    strokeNames: [],
  },
  {
    id: "shi5",
    char: "试",
    pinyin: "shì",
    group: "school",
    meaning: "试试",
    strokeNames: [],
  },
  {
    id: "shi6",
    char: "师",
    pinyin: "shī",
    group: "school",
    meaning: "老师",
    strokeNames: [],
  },
  {
    id: "ban",
    char: "班",
    pinyin: "bān",
    group: "school",
    meaning: "班级",
    strokeNames: [],
  },
  {
    id: "tong",
    char: "同",
    pinyin: "tóng",
    group: "school",
    meaning: "同学",
    strokeNames: [],
  },
  {
    id: "xin2",
    char: "新",
    pinyin: "xīn",
    group: "school",
    meaning: "新的",
    strokeNames: [],
  },
  {
    id: "jiu3",
    char: "旧",
    pinyin: "jiù",
    group: "school",
    meaning: "旧的",
    strokeNames: [],
  },
  {
    id: "chang",
    char: "长",
    pinyin: "cháng",
    group: "school",
    meaning: "长短",
    strokeNames: [],
  },
  {
    id: "gao",
    char: "高",
    pinyin: "gāo",
    group: "school",
    meaning: "高矮",
    strokeNames: [],
  },
  {
    id: "di3",
    char: "低",
    pinyin: "dī",
    group: "school",
    meaning: "高低",
    strokeNames: [],
  },
  {
    id: "man",
    char: "慢",
    pinyin: "màn",
    group: "school",
    meaning: "快慢",
    strokeNames: [],
  },
  {
    id: "zao",
    char: "早",
    pinyin: "zǎo",
    group: "school",
    meaning: "早上",
    strokeNames: [],
  },
  {
    id: "jin3",
    char: "今",
    pinyin: "jīn",
    group: "school",
    meaning: "今天",
    strokeNames: [],
  },
  {
    id: "sui",
    char: "岁",
    pinyin: "suì",
    group: "school",
    meaning: "岁数",
    strokeNames: [],
  },
  {
    id: "cai2",
    char: "才",
    pinyin: "cái",
    group: "school",
    meaning: "刚才",
    strokeNames: [],
  },
  {
    id: "you4",
    char: "又",
    pinyin: "yòu",
    group: "school",
    meaning: "又",
    strokeNames: [],
  },
  {
    id: "zai2",
    char: "再",
    pinyin: "zài",
    group: "school",
    meaning: "再",
    strokeNames: [],
  },
  {
    id: "hai3",
    char: "还",
    pinyin: "hái",
    group: "school",
    meaning: "还",
    strokeNames: [],
  },
  {
    id: "zhi3",
    char: "只",
    pinyin: "zhǐ",
    group: "school",
    meaning: "只有",
    strokeNames: [],
  },
  {
    id: "ba3",
    char: "把",
    pinyin: "bǎ",
    group: "school",
    meaning: "把",
    strokeNames: [],
  },
  {
    id: "bei2",
    char: "被",
    pinyin: "bèi",
    group: "school",
    meaning: "被",
    strokeNames: [],
  },
  {
    id: "cong",
    char: "从",
    pinyin: "cóng",
    group: "school",
    meaning: "从",
    strokeNames: [],
  },
  {
    id: "yi3",
    char: "椅",
    pinyin: "yǐ",
    group: "life",
    meaning: "椅子",
    strokeNames: [],
  },
  {
    id: "deng",
    char: "灯",
    pinyin: "dēng",
    group: "life",
    meaning: "灯",
    strokeNames: [],
  },
  {
    id: "bei3",
    char: "杯",
    pinyin: "bēi",
    group: "life",
    meaning: "杯子",
    strokeNames: [],
  },
  {
    id: "shao2",
    char: "勺",
    pinyin: "sháo",
    group: "life",
    meaning: "勺子",
    strokeNames: [],
  },
  {
    id: "mi",
    char: "米",
    pinyin: "mǐ",
    group: "life",
    meaning: "米",
    strokeNames: [],
  },
  {
    id: "bao",
    char: "包",
    pinyin: "bāo",
    group: "life",
    meaning: "包子",
    strokeNames: [],
  },
  {
    id: "rou",
    char: "肉",
    pinyin: "ròu",
    group: "life",
    meaning: "肉",
    strokeNames: [],
  },
  {
    id: "dan",
    char: "蛋",
    pinyin: "dàn",
    group: "life",
    meaning: "蛋",
    strokeNames: [],
  },
  {
    id: "tang",
    char: "糖",
    pinyin: "táng",
    group: "life",
    meaning: "糖",
    strokeNames: [],
  },
  {
    id: "you5",
    char: "油",
    pinyin: "yóu",
    group: "life",
    meaning: "油",
    strokeNames: [],
  },
  {
    id: "cha",
    char: "茶",
    pinyin: "chá",
    group: "life",
    meaning: "茶",
    strokeNames: [],
  },
  {
    id: "jiu4",
    char: "酒",
    pinyin: "jiǔ",
    group: "life",
    meaning: "酒",
    strokeNames: [],
  },
  {
    id: "e",
    char: "饿",
    pinyin: "è",
    group: "life",
    meaning: "饿",
    strokeNames: [],
  },
  {
    id: "bao2",
    char: "饱",
    pinyin: "bǎo",
    group: "life",
    meaning: "饱",
    strokeNames: [],
  },
  {
    id: "re",
    char: "热",
    pinyin: "rè",
    group: "life",
    meaning: "热",
    strokeNames: [],
  },
  {
    id: "leng",
    char: "冷",
    pinyin: "lěng",
    group: "life",
    meaning: "冷",
    strokeNames: [],
  },
  {
    id: "wen3",
    char: "温",
    pinyin: "wēn",
    group: "life",
    meaning: "温度",
    strokeNames: [],
  },
  {
    id: "qing",
    char: "清",
    pinyin: "qīng",
    group: "life",
    meaning: "清水",
    strokeNames: [],
  },
  {
    id: "xi4",
    char: "洗",
    pinyin: "xǐ",
    group: "life",
    meaning: "洗手",
    strokeNames: [],
  },
  {
    id: "zao2",
    char: "澡",
    pinyin: "zǎo",
    group: "life",
    meaning: "洗澡",
    strokeNames: [],
  },
  {
    id: "fu2",
    char: "服",
    pinyin: "fú",
    group: "life",
    meaning: "衣服",
    strokeNames: [],
  },
  {
    id: "mao2",
    char: "帽",
    pinyin: "mào",
    group: "life",
    meaning: "帽子",
    strokeNames: [],
  },
  {
    id: "xie2",
    char: "鞋",
    pinyin: "xié",
    group: "life",
    meaning: "鞋子",
    strokeNames: [],
  },
  {
    id: "wa2",
    char: "袜",
    pinyin: "wà",
    group: "life",
    meaning: "袜子",
    strokeNames: [],
  },
  {
    id: "ku",
    char: "裤",
    pinyin: "kù",
    group: "life",
    meaning: "裤子",
    strokeNames: [],
  },
  {
    id: "dai",
    char: "袋",
    pinyin: "dài",
    group: "life",
    meaning: "口袋",
    strokeNames: [],
  },
  {
    id: "mai2",
    char: "卖",
    pinyin: "mài",
    group: "life",
    meaning: "卖",
    strokeNames: [],
  },
  {
    id: "shi7",
    char: "市",
    pinyin: "shì",
    group: "life",
    meaning: "市场",
    strokeNames: [],
  },
  {
    id: "gong",
    char: "工",
    pinyin: "gōng",
    group: "life",
    meaning: "工作",
    strokeNames: [],
  },
  {
    id: "shi8",
    char: "事",
    pinyin: "shì",
    group: "life",
    meaning: "事情",
    strokeNames: [],
  },
  {
    id: "ye4",
    char: "业",
    pinyin: "yè",
    group: "life",
    meaning: "作业",
    strokeNames: [],
  },
  {
    id: "mang",
    char: "忙",
    pinyin: "máng",
    group: "life",
    meaning: "忙碌",
    strokeNames: [],
  },
  {
    id: "xiu",
    char: "休",
    pinyin: "xiū",
    group: "life",
    meaning: "休息",
    strokeNames: [],
  },
  {
    id: "xi5",
    char: "息",
    pinyin: "xī",
    group: "life",
    meaning: "休息",
    strokeNames: [],
  },
  {
    id: "bing",
    char: "病",
    pinyin: "bìng",
    group: "life",
    meaning: "生病",
    strokeNames: [],
  },
  {
    id: "yi4",
    char: "医",
    pinyin: "yī",
    group: "life",
    meaning: "医生",
    strokeNames: [],
  },
  {
    id: "yao2",
    char: "药",
    pinyin: "yào",
    group: "life",
    meaning: "药",
    strokeNames: [],
  },
  {
    id: "lei",
    char: "雷",
    pinyin: "léi",
    group: "nature",
    meaning: "打雷",
    strokeNames: [],
  },
  {
    id: "bing2",
    char: "冰",
    pinyin: "bīng",
    group: "nature",
    meaning: "冰块",
    strokeNames: [],
  },
  {
    id: "wu2",
    char: "雾",
    pinyin: "wù",
    group: "nature",
    meaning: "大雾",
    strokeNames: [],
  },
  {
    id: "lu2",
    char: "露",
    pinyin: "lù",
    group: "nature",
    meaning: "露水",
    strokeNames: [],
  },
  {
    id: "sha",
    char: "沙",
    pinyin: "shā",
    group: "nature",
    meaning: "沙子",
    strokeNames: [],
  },
  {
    id: "chen",
    char: "尘",
    pinyin: "chén",
    group: "nature",
    meaning: "灰尘",
    strokeNames: [],
  },
  {
    id: "hu2",
    char: "湖",
    pinyin: "hú",
    group: "nature",
    meaning: "湖水",
    strokeNames: [],
  },
  {
    id: "xi6",
    char: "溪",
    pinyin: "xī",
    group: "nature",
    meaning: "小溪",
    strokeNames: [],
  },
  {
    id: "cheng",
    char: "城",
    pinyin: "chéng",
    group: "nature",
    meaning: "城市",
    strokeNames: [],
  },
  {
    id: "cun",
    char: "村",
    pinyin: "cūn",
    group: "nature",
    meaning: "村子",
    strokeNames: [],
  },
  {
    id: "lin",
    char: "林",
    pinyin: "lín",
    group: "nature",
    meaning: "树林",
    strokeNames: [],
  },
  {
    id: "sen",
    char: "森",
    pinyin: "sēn",
    group: "nature",
    meaning: "森林",
    strokeNames: [],
  },
  {
    id: "zhu2",
    char: "竹",
    pinyin: "zhú",
    group: "nature",
    meaning: "竹子",
    strokeNames: [],
  },
  {
    id: "song",
    char: "松",
    pinyin: "sōng",
    group: "nature",
    meaning: "松树",
    strokeNames: [],
  },
  {
    id: "liu2",
    char: "柳",
    pinyin: "liǔ",
    group: "nature",
    meaning: "柳树",
    strokeNames: [],
  },
  {
    id: "tao",
    char: "桃",
    pinyin: "táo",
    group: "nature",
    meaning: "桃子",
    strokeNames: [],
  },
  {
    id: "li2",
    char: "梨",
    pinyin: "lí",
    group: "nature",
    meaning: "梨",
    strokeNames: [],
  },
  {
    id: "xing2",
    char: "杏",
    pinyin: "xìng",
    group: "nature",
    meaning: "杏",
    strokeNames: [],
  },
  {
    id: "dou2",
    char: "豆",
    pinyin: "dòu",
    group: "nature",
    meaning: "豆子",
    strokeNames: [],
  },
  {
    id: "shu5",
    char: "蔬",
    pinyin: "shū",
    group: "nature",
    meaning: "蔬菜",
    strokeNames: [],
  },
  {
    id: "feng2",
    char: "蜂",
    pinyin: "fēng",
    group: "animal",
    meaning: "蜜蜂",
    strokeNames: [],
  },
  {
    id: "die",
    char: "蝶",
    pinyin: "dié",
    group: "animal",
    meaning: "蝴蝶",
    strokeNames: [],
  },
  {
    id: "yi5",
    char: "蚁",
    pinyin: "yǐ",
    group: "animal",
    meaning: "蚂蚁",
    strokeNames: [],
  },
  {
    id: "zhu3",
    char: "蛛",
    pinyin: "zhū",
    group: "animal",
    meaning: "蜘蛛",
    strokeNames: [],
  },
  {
    id: "gui",
    char: "龟",
    pinyin: "guī",
    group: "animal",
    meaning: "乌龟",
    strokeNames: [],
  },
  {
    id: "jing",
    char: "鲸",
    pinyin: "jīng",
    group: "animal",
    meaning: "鲸鱼",
    strokeNames: [],
  },
  {
    id: "e2",
    char: "鹅",
    pinyin: "é",
    group: "animal",
    meaning: "鹅",
    strokeNames: [],
  },
  {
    id: "ge3",
    char: "鸽",
    pinyin: "gē",
    group: "animal",
    meaning: "鸽子",
    strokeNames: [],
  },
  {
    id: "ying",
    char: "鹰",
    pinyin: "yīng",
    group: "animal",
    meaning: "老鹰",
    strokeNames: [],
  },
  {
    id: "ya3",
    char: "鸦",
    pinyin: "yā",
    group: "animal",
    meaning: "乌鸦",
    strokeNames: [],
  },
  {
    id: "que",
    char: "雀",
    pinyin: "què",
    group: "animal",
    meaning: "麻雀",
    strokeNames: [],
  },
  {
    id: "shi9",
    char: "狮",
    pinyin: "shī",
    group: "animal",
    meaning: "狮子",
    strokeNames: [],
  },
  {
    id: "lang",
    char: "狼",
    pinyin: "láng",
    group: "animal",
    meaning: "狼",
    strokeNames: [],
  },
  {
    id: "hu3",
    char: "狐",
    pinyin: "hú",
    group: "animal",
    meaning: "狐狸",
    strokeNames: [],
  },
  {
    id: "lu3",
    char: "鹿",
    pinyin: "lù",
    group: "animal",
    meaning: "鹿",
    strokeNames: [],
  },
  {
    id: "lv2",
    char: "驴",
    pinyin: "lǘ",
    group: "animal",
    meaning: "驴",
    strokeNames: [],
  },
  {
    id: "can",
    char: "蚕",
    pinyin: "cán",
    group: "animal",
    meaning: "蚕",
    strokeNames: [],
  },
  {
    id: "ying2",
    char: "蝇",
    pinyin: "yíng",
    group: "animal",
    meaning: "苍蝇",
    strokeNames: [],
  },
  {
    id: "wen4",
    char: "蚊",
    pinyin: "wén",
    group: "animal",
    meaning: "蚊子",
    strokeNames: [],
  },
  {
    id: "xie3",
    char: "蟹",
    pinyin: "xiè",
    group: "animal",
    meaning: "螃蟹",
    strokeNames: [],
  },
  {
    id: "ke3",
    char: "蝌",
    pinyin: "kē",
    group: "animal",
    meaning: "蝌蚪",
    strokeNames: [],
  },
  {
    id: "dou3",
    char: "蚪",
    pinyin: "dǒu",
    group: "animal",
    meaning: "蝌蚪",
    strokeNames: [],
  },
  {
    id: "bao3",
    char: "豹",
    pinyin: "bào",
    group: "animal",
    meaning: "豹子",
    strokeNames: [],
  },
  {
    id: "wang",
    char: "王",
    pinyin: "wáng",
    group: "body",
    meaning: "姓王",
    strokeNames: [],
  },
  {
    id: "li3",
    char: "李",
    pinyin: "lǐ",
    group: "body",
    meaning: "姓李",
    strokeNames: [],
  },
  {
    id: "zhang",
    char: "张",
    pinyin: "zhāng",
    group: "body",
    meaning: "姓张",
    strokeNames: [],
  },
  {
    id: "liu3",
    char: "刘",
    pinyin: "liú",
    group: "body",
    meaning: "姓刘",
    strokeNames: [],
  },
  {
    id: "chen2",
    char: "陈",
    pinyin: "chén",
    group: "body",
    meaning: "姓陈",
    strokeNames: [],
  },
  {
    id: "yang3",
    char: "杨",
    pinyin: "yáng",
    group: "body",
    meaning: "姓杨",
    strokeNames: [],
  },
  {
    id: "zhao2",
    char: "赵",
    pinyin: "zhào",
    group: "body",
    meaning: "姓赵",
    strokeNames: [],
  },
  {
    id: "zhou",
    char: "周",
    pinyin: "zhōu",
    group: "body",
    meaning: "姓周",
    strokeNames: [],
  },
  {
    id: "wu3",
    char: "吴",
    pinyin: "wú",
    group: "body",
    meaning: "姓吴",
    strokeNames: [],
  },
  {
    id: "xu",
    char: "徐",
    pinyin: "xú",
    group: "body",
    meaning: "姓徐",
    strokeNames: [],
  },
  {
    id: "sun",
    char: "孙",
    pinyin: "sūn",
    group: "body",
    meaning: "姓孙",
    strokeNames: [],
  },
  {
    id: "zhu4",
    char: "朱",
    pinyin: "zhū",
    group: "body",
    meaning: "姓朱",
    strokeNames: [],
  },
  {
    id: "hu4",
    char: "胡",
    pinyin: "hú",
    group: "body",
    meaning: "姓胡",
    strokeNames: [],
  },
  {
    id: "zheng2",
    char: "郑",
    pinyin: "zhèng",
    group: "body",
    meaning: "姓郑",
    strokeNames: [],
  },
];


/** 轻声助词不入库（的/了/着/过/吗/呢/么/们…） */
const LIGHT_TONE_CHARS = new Set(["的", "了", "着", "过", "吗", "呢", "么", "们", "啊", "吧", "嘛", "啦"]);

/**
 * 与 BV1RrySBCEmt《汉语拼音跟我读一读》屏幕韵母表一致的 24 个韵母。
 * 不含 ian/uo/iao/uang 等扩展拼写；字库只保留可用该表拼出的字。
 */
const CHART_FINALS = new Set([
  "a", "o", "e", "i", "u", "v",
  "ai", "ei", "ui", "ao", "ou", "iu", "ie", "ve", "er",
  "an", "en", "in", "un", "vn",
  "ang", "eng", "ing", "ong",
]);

const CHART_INITIALS = [
  "zh", "ch", "sh", "b", "p", "m", "f", "d", "t", "n", "l",
  "g", "k", "h", "j", "q", "x", "r", "z", "c", "s", "y", "w",
];

function stripTonePlain(pinyin) {
  return String(pinyin || "")
    .replace(/[ǖǘǚǜü]/g, "v")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[āáǎà]/g, "a")
    .replace(/[ēéěè]/g, "e")
    .replace(/[īíǐì]/g, "i")
    .replace(/[ōóǒò]/g, "o")
    .replace(/[ūúǔù]/g, "u")
    .toLowerCase()
    .replace(/[^a-z]/g, "");
}

function chartFinalKey(finalPlain, initial) {
  let f = (finalPlain || "").toLowerCase().replace(/ü/g, "v");
  const aliases = { ue: "ve", üe: "ve", ün: "vn", uen: "un", uei: "ui", iou: "iu" };
  f = aliases[f] || f;
  // j/q/x/y 后的 u = ü
  if ((initial === "j" || initial === "q" || initial === "x") && f.startsWith("u") && !f.startsWith("uo")) {
    f = `v${f.slice(1)}`;
  }
  if (initial === "y" && f.startsWith("u") && f !== "ou") {
    f = `v${f.slice(1)}`;
  }
  return f;
}

/** 音节的声母+韵母是否落在视频字表内 */
function isChartSyllable(pinyin) {
  let plain = stripTonePlain(pinyin);
  if (!plain) return false;
  let initial = "";
  for (const ini of CHART_INITIALS) {
    if (plain.startsWith(ini)) {
      initial = ini;
      plain = plain.slice(ini.length) || plain;
      break;
    }
  }
  const finalKey = chartFinalKey(plain, initial);
  if (!CHART_FINALS.has(finalKey)) return false;
  if (initial && !CHART_INITIALS.includes(initial)) return false;
  return true;
}

// 兜底：剔除轻声助词 + 非视频字表组合；导出时再按新华字典音序排
const CHARACTERS_FILTERED = CHARACTERS_RAW.filter(
  (c) => !LIGHT_TONE_CHARS.has(c.char) && isChartSyllable(c.pinyin)
);

export function getCharacter(id) {
  return CHARACTERS.find((c) => c.id === id);
}

/** 《新华字典》音序：A–Z 26 字母 */
export const XINHUA_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

const TONE_MARK = {
  "ā": 1, "á": 2, "ǎ": 3, "à": 4,
  "ē": 1, "é": 2, "ě": 3, "è": 4,
  "ī": 1, "í": 2, "ǐ": 3, "ì": 4,
  "ō": 1, "ó": 2, "ǒ": 3, "ò": 4,
  "ū": 1, "ú": 2, "ǔ": 3, "ù": 4,
  "ǖ": 1, "ǘ": 2, "ǚ": 3, "ǜ": 4,
  "ń": 2, "ň": 3, "ǹ": 4,
};

function pinyinTone(pinyin) {
  for (const ch of String(pinyin || "")) {
    if (TONE_MARK[ch]) return TONE_MARK[ch];
  }
  const nfd = String(pinyin || "").normalize("NFD");
  if (nfd.includes("\u0304")) return 1;
  if (nfd.includes("\u0301")) return 2;
  if (nfd.includes("\u030c")) return 3;
  if (nfd.includes("\u0300")) return 4;
  return 5;
}

/** 拼音首字母（zh/ch/sh 分别归 Z/C/S），与新华字典音序检字一致 */
export function pinyinLetter(pinyin) {
  const plain = stripTonePlain(pinyin);
  return (plain[0] || "").toUpperCase();
}

function strokeCount(c) {
  const n = (c.strokeNames || []).length;
  return n > 0 ? n : 99;
}

/** 同音：阴平→阳平→上声→去声→轻声；再按笔画少到多 */
export function compareXinhua(a, b) {
  const pa = stripTonePlain(a.pinyin);
  const pb = stripTonePlain(b.pinyin);
  if (pa !== pb) return pa < pb ? -1 : 1;
  const ta = pinyinTone(a.pinyin);
  const tb = pinyinTone(b.pinyin);
  if (ta !== tb) return ta - tb;
  const sa = strokeCount(a);
  const sb = strokeCount(b);
  if (sa !== sb) return sa - sb;
  return String(a.char).localeCompare(String(b.char), "zh-CN");
}

export const CHARACTERS = CHARACTERS_FILTERED.slice().sort(compareXinhua);

export function charactersByGroup(groupId) {
  if (!groupId || groupId === "all") return CHARACTERS;
  return CHARACTERS.filter((c) => c.group === groupId);
}
