/**
 * 汉字关卡字库（常用字 200 个）
 *
 * 字库编排与识字思路参考：
 *   陈迪业《画给孩子的汉字书》
 *   福建科学技术出版社，2021年2月
 *   ISBN 978-7-5335-6365-3
 *
 * 描红字模数据来自 Hanzi Writer。
 */

export const BOOK_SOURCE = {
  title: "画给孩子的汉字书",
  author: "陈迪业",
  publisher: "福建科学技术出版社",
  year: "2021",
  isbn: "978-7-5335-6365-3",
  credit:
    "字库与识字思路参考陈迪业《画给孩子的汉字书》（福建科学技术出版社，ISBN 978-7-5335-6365-3）",
};

export const GROUPS = [
  { id: "all", name: "全部" },
  { id: "nature", name: "自然" },
  { id: "body", name: "人物" },
  { id: "life", name: "生活" },
  { id: "animal", name: "动物" },
  { id: "school", name: "学习" },
];

const CHARACTERS_RAW = [
  // —— 学习 ——
  {
    id: "yi",
    char: "一",
    pinyin: "yī",
    group: "school",
    meaning: "数字一",
    strokeNames: [],
  },
  {
    id: "er",
    char: "二",
    pinyin: "èr",
    group: "school",
    meaning: "数字二",
    strokeNames: [],
  },
  {
    id: "san",
    char: "三",
    pinyin: "sān",
    group: "school",
    meaning: "数字三",
    strokeNames: [],
  },
  {
    id: "si",
    char: "四",
    pinyin: "sì",
    group: "school",
    meaning: "数字四",
    strokeNames: [],
  },
  {
    id: "wu",
    char: "五",
    pinyin: "wǔ",
    group: "school",
    meaning: "数字五",
    strokeNames: [],
  },
  {
    id: "liu",
    char: "六",
    pinyin: "liù",
    group: "school",
    meaning: "数字六",
    strokeNames: [],
  },
  {
    id: "qi",
    char: "七",
    pinyin: "qī",
    group: "school",
    meaning: "数字七",
    strokeNames: [],
  },
  {
    id: "ba",
    char: "八",
    pinyin: "bā",
    group: "school",
    meaning: "数字八",
    strokeNames: [],
  },
  {
    id: "jiu",
    char: "九",
    pinyin: "jiǔ",
    group: "school",
    meaning: "数字九",
    strokeNames: [],
  },
  {
    id: "shi",
    char: "十",
    pinyin: "shí",
    group: "school",
    meaning: "数字十",
    strokeNames: [],
  },
  {
    id: "bai",
    char: "百",
    pinyin: "bǎi",
    group: "school",
    meaning: "一百",
    strokeNames: [],
  },
  {
    id: "qian",
    char: "千",
    pinyin: "qiān",
    group: "school",
    meaning: "一千",
    strokeNames: [],
  },
  {
    id: "wan",
    char: "万",
    pinyin: "wàn",
    group: "school",
    meaning: "一万",
    strokeNames: [],
  },
  {
    id: "bu",
    char: "不",
    pinyin: "bù",
    group: "school",
    meaning: "不",
    strokeNames: [],
  },
  {
    id: "ye",
    char: "也",
    pinyin: "yě",
    group: "school",
    meaning: "也",
    strokeNames: [],
  },
  {
    id: "hen",
    char: "很",
    pinyin: "hěn",
    group: "school",
    meaning: "很",
    strokeNames: [],
  },
  {
    id: "zui",
    char: "最",
    pinyin: "zuì",
    group: "school",
    meaning: "最",
    strokeNames: [],
  },
  {
    id: "tai",
    char: "太",
    pinyin: "tài",
    group: "school",
    meaning: "太",
    strokeNames: [],
  },
  {
    id: "dou",
    char: "都",
    pinyin: "dōu",
    group: "school",
    meaning: "都",
    strokeNames: [],
  },
  {
    id: "jiu2",
    char: "就",
    pinyin: "jiù",
    group: "school",
    meaning: "就",
    strokeNames: [],
  },
  {
    id: "he",
    char: "和",
    pinyin: "hé",
    group: "school",
    meaning: "和",
    strokeNames: [],
  },
  {
    id: "shi2",
    char: "是",
    pinyin: "shì",
    group: "school",
    meaning: "是",
    strokeNames: [],
  },
  {
    id: "you",
    char: "有",
    pinyin: "yǒu",
    group: "school",
    meaning: "有",
    strokeNames: [],
  },
  {
    id: "mei",
    char: "没",
    pinyin: "méi",
    group: "school",
    meaning: "没有",
    strokeNames: [],
  },
  {
    id: "zai",
    char: "在",
    pinyin: "zài",
    group: "school",
    meaning: "在",
    strokeNames: [],
  },
  {
    id: "zhe2",
    char: "这",
    pinyin: "zhè",
    group: "school",
    meaning: "这",
    strokeNames: [],
  },
  {
    id: "na",
    char: "那",
    pinyin: "nà",
    group: "school",
    meaning: "那",
    strokeNames: [],
  },
  {
    id: "shen",
    char: "什",
    pinyin: "shén",
    group: "school",
    meaning: "什么",
    strokeNames: [],
  },
  {
    id: "shui",
    char: "谁",
    pinyin: "shuí",
    group: "school",
    meaning: "谁",
    strokeNames: [],
  },
  {
    id: "na2",
    char: "哪",
    pinyin: "nǎ",
    group: "school",
    meaning: "哪",
    strokeNames: [],
  },
  {
    id: "ji",
    char: "几",
    pinyin: "jǐ",
    group: "school",
    meaning: "几",
    strokeNames: [],
  },
  {
    id: "zen",
    char: "怎",
    pinyin: "zěn",
    group: "school",
    meaning: "怎么",
    strokeNames: [],
  },
  {
    id: "wei",
    char: "为",
    pinyin: "wèi",
    group: "school",
    meaning: "为",
    strokeNames: [],
  },
  {
    id: "neng",
    char: "能",
    pinyin: "néng",
    group: "school",
    meaning: "能",
    strokeNames: [],
  },
  {
    id: "hui",
    char: "会",
    pinyin: "huì",
    group: "school",
    meaning: "会",
    strokeNames: [],
  },
  {
    id: "ke",
    char: "可",
    pinyin: "kě",
    group: "school",
    meaning: "可以",
    strokeNames: [],
  },
  {
    id: "yao",
    char: "要",
    pinyin: "yào",
    group: "school",
    meaning: "要",
    strokeNames: [],
  },
  {
    id: "zhi",
    char: "知",
    pinyin: "zhī",
    group: "school",
    meaning: "知道",
    strokeNames: [],
  },
  {
    id: "dao",
    char: "道",
    pinyin: "dào",
    group: "school",
    meaning: "道理",
    strokeNames: [],
  },
  {
    id: "shuo",
    char: "说",
    pinyin: "shuō",
    group: "school",
    meaning: "说",
    strokeNames: [],
  },
  {
    id: "hua",
    char: "话",
    pinyin: "huà",
    group: "school",
    meaning: "话",
    strokeNames: [],
  },
  {
    id: "xue",
    char: "学",
    pinyin: "xué",
    group: "school",
    meaning: "学",
    strokeNames: [],
  },
  {
    id: "xi",
    char: "习",
    pinyin: "xí",
    group: "school",
    meaning: "习",
    strokeNames: [],
  },
  // —— 人物 ——
  {
    id: "wo",
    char: "我",
    pinyin: "wǒ",
    group: "body",
    meaning: "我",
    strokeNames: [],
  },
  {
    id: "ni",
    char: "你",
    pinyin: "nǐ",
    group: "body",
    meaning: "你",
    strokeNames: [],
  },
  {
    id: "ta",
    char: "他",
    pinyin: "tā",
    group: "body",
    meaning: "他",
    strokeNames: [],
  },
  {
    id: "ta2",
    char: "她",
    pinyin: "tā",
    group: "body",
    meaning: "她",
    strokeNames: [],
  },
  {
    id: "ren",
    char: "人",
    pinyin: "rén",
    group: "body",
    meaning: "人",
    strokeNames: ["撇", "捺"],
  },
  {
    id: "da",
    char: "大",
    pinyin: "dà",
    group: "body",
    meaning: "大",
    strokeNames: ["横", "撇", "捺"],
  },
  {
    id: "xiao",
    char: "小",
    pinyin: "xiǎo",
    group: "body",
    meaning: "小",
    strokeNames: ["竖钩", "撇", "点"],
  },
  {
    id: "kou",
    char: "口",
    pinyin: "kǒu",
    group: "body",
    meaning: "口",
    strokeNames: ["竖", "横折", "横"],
  },
  {
    id: "mu",
    char: "目",
    pinyin: "mù",
    group: "body",
    meaning: "眼睛",
    strokeNames: ["竖", "横折", "横", "横", "横"],
  },
  {
    id: "shou",
    char: "手",
    pinyin: "shǒu",
    group: "body",
    meaning: "手",
    strokeNames: ["撇", "横", "横", "竖钩"],
  },
  {
    id: "zu",
    char: "足",
    pinyin: "zú",
    group: "body",
    meaning: "脚",
    strokeNames: ["竖", "横折", "横", "竖", "横", "撇", "捺"],
  },
  {
    id: "xin",
    char: "心",
    pinyin: "xīn",
    group: "body",
    meaning: "心",
    strokeNames: ["点", "斜钩", "点", "点"],
  },
  {
    id: "er2",
    char: "耳",
    pinyin: "ěr",
    group: "body",
    meaning: "耳朵",
    strokeNames: ["横", "竖", "竖", "横", "横", "横"],
  },
  {
    id: "tou",
    char: "头",
    pinyin: "tóu",
    group: "body",
    meaning: "头",
    strokeNames: [],
  },
  {
    id: "mian",
    char: "面",
    pinyin: "miàn",
    group: "body",
    meaning: "脸",
    strokeNames: [],
  },
  {
    id: "ya",
    char: "牙",
    pinyin: "yá",
    group: "body",
    meaning: "牙",
    strokeNames: [],
  },
  {
    id: "fa",
    char: "发",
    pinyin: "fà",
    group: "body",
    meaning: "头发",
    strokeNames: [],
  },
  {
    id: "shen2",
    char: "身",
    pinyin: "shēn",
    group: "body",
    meaning: "身体",
    strokeNames: [],
  },
  {
    id: "nan",
    char: "男",
    pinyin: "nán",
    group: "body",
    meaning: "男",
    strokeNames: [],
  },
  {
    id: "nv",
    char: "女",
    pinyin: "nǚ",
    group: "body",
    meaning: "女",
    strokeNames: ["撇点", "撇", "横"],
  },
  {
    id: "zi",
    char: "子",
    pinyin: "zǐ",
    group: "body",
    meaning: "孩子",
    strokeNames: ["横撇", "竖钩", "横"],
  },
  {
    id: "fu",
    char: "父",
    pinyin: "fù",
    group: "body",
    meaning: "父亲",
    strokeNames: [],
  },
  {
    id: "mu2",
    char: "母",
    pinyin: "mǔ",
    group: "body",
    meaning: "母亲",
    strokeNames: [],
  },
  {
    id: "ba2",
    char: "爸",
    pinyin: "bà",
    group: "body",
    meaning: "爸爸",
    strokeNames: [],
  },
  {
    id: "ma2",
    char: "妈",
    pinyin: "mā",
    group: "body",
    meaning: "妈妈",
    strokeNames: [],
  },
  {
    id: "ge",
    char: "哥",
    pinyin: "gē",
    group: "body",
    meaning: "哥哥",
    strokeNames: [],
  },
  {
    id: "jie",
    char: "姐",
    pinyin: "jiě",
    group: "body",
    meaning: "姐姐",
    strokeNames: [],
  },
  {
    id: "di",
    char: "弟",
    pinyin: "dì",
    group: "body",
    meaning: "弟弟",
    strokeNames: [],
  },
  {
    id: "mei2",
    char: "妹",
    pinyin: "mèi",
    group: "body",
    meaning: "妹妹",
    strokeNames: [],
  },
  {
    id: "ye2",
    char: "爷",
    pinyin: "yé",
    group: "body",
    meaning: "爷爷",
    strokeNames: [],
  },
  {
    id: "nai",
    char: "奶",
    pinyin: "nǎi",
    group: "body",
    meaning: "奶奶",
    strokeNames: [],
  },
  {
    id: "hai",
    char: "孩",
    pinyin: "hái",
    group: "body",
    meaning: "孩子",
    strokeNames: [],
  },
  {
    id: "you2",
    char: "友",
    pinyin: "yǒu",
    group: "body",
    meaning: "朋友",
    strokeNames: [],
  },
  {
    id: "lao",
    char: "老",
    pinyin: "lǎo",
    group: "body",
    meaning: "老",
    strokeNames: [],
  },
  {
    id: "shao",
    char: "少",
    pinyin: "shǎo",
    group: "body",
    meaning: "少",
    strokeNames: [],
  },
  {
    id: "hao",
    char: "好",
    pinyin: "hǎo",
    group: "body",
    meaning: "好",
    strokeNames: [],
  },
  {
    id: "ai",
    char: "爱",
    pinyin: "ài",
    group: "body",
    meaning: "爱",
    strokeNames: [],
  },
  {
    id: "xi2",
    char: "喜",
    pinyin: "xǐ",
    group: "body",
    meaning: "喜欢",
    strokeNames: [],
  },
  {
    id: "huan",
    char: "欢",
    pinyin: "huān",
    group: "body",
    meaning: "欢乐",
    strokeNames: [],
  },
  // —— 生活 ——
  {
    id: "shang",
    char: "上",
    pinyin: "shàng",
    group: "life",
    meaning: "上面",
    strokeNames: ["竖", "横", "横"],
  },
  {
    id: "xia",
    char: "下",
    pinyin: "xià",
    group: "life",
    meaning: "下面",
    strokeNames: ["横", "竖", "点"],
  },
  {
    id: "zhong",
    char: "中",
    pinyin: "zhōng",
    group: "life",
    meaning: "中间",
    strokeNames: ["竖", "横折", "横", "竖"],
  },
  {
    id: "zuo",
    char: "左",
    pinyin: "zuǒ",
    group: "life",
    meaning: "左边",
    strokeNames: [],
  },
  {
    id: "you3",
    char: "右",
    pinyin: "yòu",
    group: "life",
    meaning: "右边",
    strokeNames: [],
  },
  {
    id: "qian2",
    char: "前",
    pinyin: "qián",
    group: "life",
    meaning: "前面",
    strokeNames: [],
  },
  {
    id: "hou",
    char: "后",
    pinyin: "hòu",
    group: "life",
    meaning: "后面",
    strokeNames: [],
  },
  {
    id: "li",
    char: "里",
    pinyin: "lǐ",
    group: "life",
    meaning: "里面",
    strokeNames: [],
  },
  {
    id: "wai",
    char: "外",
    pinyin: "wài",
    group: "life",
    meaning: "外面",
    strokeNames: [],
  },
  {
    id: "dong",
    char: "东",
    pinyin: "dōng",
    group: "life",
    meaning: "东方",
    strokeNames: [],
  },
  {
    id: "nan2",
    char: "南",
    pinyin: "nán",
    group: "life",
    meaning: "南方",
    strokeNames: [],
  },
  {
    id: "xi3",
    char: "西",
    pinyin: "xī",
    group: "life",
    meaning: "西方",
    strokeNames: [],
  },
  {
    id: "bei",
    char: "北",
    pinyin: "běi",
    group: "life",
    meaning: "北方",
    strokeNames: [],
  },
  {
    id: "lai",
    char: "来",
    pinyin: "lái",
    group: "life",
    meaning: "来",
    strokeNames: [],
  },
  {
    id: "qu",
    char: "去",
    pinyin: "qù",
    group: "life",
    meaning: "去",
    strokeNames: [],
  },
  {
    id: "hui2",
    char: "回",
    pinyin: "huí",
    group: "life",
    meaning: "回",
    strokeNames: [],
  },
  {
    id: "chu",
    char: "出",
    pinyin: "chū",
    group: "life",
    meaning: "出",
    strokeNames: [],
  },
  {
    id: "jin",
    char: "进",
    pinyin: "jìn",
    group: "life",
    meaning: "进",
    strokeNames: [],
  },
  {
    id: "dao2",
    char: "到",
    pinyin: "dào",
    group: "life",
    meaning: "到",
    strokeNames: [],
  },
  {
    id: "kan",
    char: "看",
    pinyin: "kàn",
    group: "life",
    meaning: "看",
    strokeNames: [],
  },
  {
    id: "ting",
    char: "听",
    pinyin: "tīng",
    group: "life",
    meaning: "听",
    strokeNames: [],
  },
  {
    id: "chi",
    char: "吃",
    pinyin: "chī",
    group: "life",
    meaning: "吃",
    strokeNames: [],
  },
  {
    id: "he2",
    char: "喝",
    pinyin: "hē",
    group: "life",
    meaning: "喝",
    strokeNames: [],
  },
  {
    id: "shui2",
    char: "睡",
    pinyin: "shuì",
    group: "life",
    meaning: "睡",
    strokeNames: [],
  },
  {
    id: "zou",
    char: "走",
    pinyin: "zǒu",
    group: "life",
    meaning: "走",
    strokeNames: [],
  },
  {
    id: "pao",
    char: "跑",
    pinyin: "pǎo",
    group: "life",
    meaning: "跑",
    strokeNames: [],
  },
  {
    id: "zuo2",
    char: "坐",
    pinyin: "zuò",
    group: "life",
    meaning: "坐",
    strokeNames: [],
  },
  {
    id: "zhan",
    char: "站",
    pinyin: "zhàn",
    group: "life",
    meaning: "站",
    strokeNames: [],
  },
  {
    id: "fei",
    char: "飞",
    pinyin: "fēi",
    group: "life",
    meaning: "飞",
    strokeNames: [],
  },
  {
    id: "wan2",
    char: "玩",
    pinyin: "wán",
    group: "life",
    meaning: "玩",
    strokeNames: [],
  },
  {
    id: "mai",
    char: "买",
    pinyin: "mǎi",
    group: "life",
    meaning: "买",
    strokeNames: [],
  },
  {
    id: "gei",
    char: "给",
    pinyin: "gěi",
    group: "life",
    meaning: "给",
    strokeNames: [],
  },
  {
    id: "yong",
    char: "用",
    pinyin: "yòng",
    group: "life",
    meaning: "用",
    strokeNames: [],
  },
  {
    id: "zuo3",
    char: "做",
    pinyin: "zuò",
    group: "life",
    meaning: "做",
    strokeNames: [],
  },
  {
    id: "da2",
    char: "打",
    pinyin: "dǎ",
    group: "life",
    meaning: "打",
    strokeNames: [],
  },
  {
    id: "zhao",
    char: "找",
    pinyin: "zhǎo",
    group: "life",
    meaning: "找",
    strokeNames: [],
  },
  {
    id: "na3",
    char: "拿",
    pinyin: "ná",
    group: "life",
    meaning: "拿",
    strokeNames: [],
  },
  {
    id: "fang",
    char: "放",
    pinyin: "fàng",
    group: "life",
    meaning: "放",
    strokeNames: [],
  },
  {
    id: "kai",
    char: "开",
    pinyin: "kāi",
    group: "life",
    meaning: "开",
    strokeNames: ["横", "横", "撇", "竖"],
  },
  {
    id: "guan",
    char: "关",
    pinyin: "guān",
    group: "life",
    meaning: "关",
    strokeNames: [],
  },
  {
    id: "men2",
    char: "门",
    pinyin: "mén",
    group: "life",
    meaning: "门",
    strokeNames: ["点", "竖", "横折钩"],
  },
  {
    id: "jia",
    char: "家",
    pinyin: "jiā",
    group: "life",
    meaning: "家",
    strokeNames: [],
  },
  {
    id: "fang2",
    char: "房",
    pinyin: "fáng",
    group: "life",
    meaning: "房",
    strokeNames: [],
  },
  {
    id: "che",
    char: "车",
    pinyin: "chē",
    group: "life",
    meaning: "车",
    strokeNames: ["横", "撇折", "横", "竖"],
  },
  {
    id: "lu",
    char: "路",
    pinyin: "lù",
    group: "life",
    meaning: "路",
    strokeNames: [],
  },
  {
    id: "shu",
    char: "书",
    pinyin: "shū",
    group: "life",
    meaning: "书",
    strokeNames: [],
  },
  {
    id: "yi2",
    char: "衣",
    pinyin: "yī",
    group: "life",
    meaning: "衣服",
    strokeNames: [],
  },
  {
    id: "fan",
    char: "饭",
    pinyin: "fàn",
    group: "life",
    meaning: "饭",
    strokeNames: [],
  },
  {
    id: "cai",
    char: "菜",
    pinyin: "cài",
    group: "life",
    meaning: "菜",
    strokeNames: [],
  },
  {
    id: "shui3",
    char: "水",
    pinyin: "shuǐ",
    group: "life",
    meaning: "水",
    strokeNames: ["竖钩", "横撇", "撇", "捺"],
  },
  // —— 自然 ——
  {
    id: "ri",
    char: "日",
    pinyin: "rì",
    group: "nature",
    meaning: "太阳 · 日子",
    strokeNames: ["竖", "横折", "横", "横"],
  },
  {
    id: "yue",
    char: "月",
    pinyin: "yuè",
    group: "nature",
    meaning: "月亮",
    strokeNames: ["撇", "横折钩", "横", "横"],
  },
  {
    id: "shan",
    char: "山",
    pinyin: "shān",
    group: "nature",
    meaning: "山",
    strokeNames: ["竖", "竖折", "竖"],
  },
  {
    id: "huo",
    char: "火",
    pinyin: "huǒ",
    group: "nature",
    meaning: "火",
    strokeNames: ["点", "撇", "撇", "捺"],
  },
  {
    id: "mu3",
    char: "木",
    pinyin: "mù",
    group: "nature",
    meaning: "木",
    strokeNames: ["横", "竖", "撇", "捺"],
  },
  {
    id: "tu",
    char: "土",
    pinyin: "tǔ",
    group: "nature",
    meaning: "土",
    strokeNames: ["横", "竖", "横"],
  },
  {
    id: "shi3",
    char: "石",
    pinyin: "shí",
    group: "nature",
    meaning: "石",
    strokeNames: ["横", "撇", "竖", "横折", "横"],
  },
  {
    id: "tian",
    char: "田",
    pinyin: "tián",
    group: "nature",
    meaning: "田",
    strokeNames: ["竖", "横折", "横", "竖", "横"],
  },
  {
    id: "tian2",
    char: "天",
    pinyin: "tiān",
    group: "nature",
    meaning: "天",
    strokeNames: ["横", "横", "撇", "捺"],
  },
  {
    id: "yu",
    char: "雨",
    pinyin: "yǔ",
    group: "nature",
    meaning: "雨",
    strokeNames: ["横", "竖", "横折钩", "点", "点", "点", "点", "点"],
  },
  {
    id: "yun",
    char: "云",
    pinyin: "yún",
    group: "nature",
    meaning: "云",
    strokeNames: ["横", "横", "撇折", "点"],
  },
  {
    id: "feng",
    char: "风",
    pinyin: "fēng",
    group: "nature",
    meaning: "风",
    strokeNames: ["撇", "横折弯钩", "撇", "点"],
  },
  {
    id: "dian",
    char: "电",
    pinyin: "diàn",
    group: "nature",
    meaning: "电",
    strokeNames: ["竖", "横折", "横", "竖", "竖弯钩"],
  },
  {
    id: "xing",
    char: "星",
    pinyin: "xīng",
    group: "nature",
    meaning: "星",
    strokeNames: ["竖", "横折", "横", "横", "撇", "横", "横", "竖", "横"],
  },
  {
    id: "xue2",
    char: "雪",
    pinyin: "xuě",
    group: "nature",
    meaning: "雪",
    strokeNames: [],
  },
  {
    id: "hua2",
    char: "花",
    pinyin: "huā",
    group: "nature",
    meaning: "花",
    strokeNames: ["横", "竖", "竖", "撇", "竖弯钩", "撇", "竖弯钩"],
  },
  {
    id: "cao",
    char: "草",
    pinyin: "cǎo",
    group: "nature",
    meaning: "草",
    strokeNames: ["横", "竖", "竖", "竖", "横折", "横", "横", "横", "竖"],
  },
  {
    id: "shu2",
    char: "树",
    pinyin: "shù",
    group: "nature",
    meaning: "树",
    strokeNames: [],
  },
  {
    id: "ye3",
    char: "叶",
    pinyin: "yè",
    group: "nature",
    meaning: "叶",
    strokeNames: [],
  },
  {
    id: "guo2",
    char: "果",
    pinyin: "guǒ",
    group: "nature",
    meaning: "果",
    strokeNames: ["竖", "横折", "横", "横", "横", "竖", "撇", "捺"],
  },
  {
    id: "chun",
    char: "春",
    pinyin: "chūn",
    group: "nature",
    meaning: "春",
    strokeNames: ["横", "横", "横", "撇", "捺", "竖", "横折", "横", "横"],
  },
  {
    id: "xia2",
    char: "夏",
    pinyin: "xià",
    group: "nature",
    meaning: "夏",
    strokeNames: [],
  },
  {
    id: "qiu",
    char: "秋",
    pinyin: "qiū",
    group: "nature",
    meaning: "秋",
    strokeNames: [],
  },
  {
    id: "dong2",
    char: "冬",
    pinyin: "dōng",
    group: "nature",
    meaning: "冬",
    strokeNames: [],
  },
  {
    id: "jiang",
    char: "江",
    pinyin: "jiāng",
    group: "nature",
    meaning: "江",
    strokeNames: [],
  },
  {
    id: "he3",
    char: "河",
    pinyin: "hé",
    group: "nature",
    meaning: "河",
    strokeNames: [],
  },
  {
    id: "hai2",
    char: "海",
    pinyin: "hǎi",
    group: "nature",
    meaning: "海",
    strokeNames: [],
  },
  {
    id: "guang",
    char: "光",
    pinyin: "guāng",
    group: "nature",
    meaning: "光",
    strokeNames: [],
  },
  {
    id: "ming",
    char: "明",
    pinyin: "míng",
    group: "nature",
    meaning: "明",
    strokeNames: ["竖", "横折", "横", "横", "撇", "横折钩", "横", "横"],
  },
  {
    id: "kong",
    char: "空",
    pinyin: "kōng",
    group: "nature",
    meaning: "空",
    strokeNames: [],
  },
  {
    id: "di2",
    char: "地",
    pinyin: "dì",
    group: "nature",
    meaning: "地",
    strokeNames: [],
  },
  {
    id: "qi2",
    char: "气",
    pinyin: "qì",
    group: "nature",
    meaning: "气",
    strokeNames: [],
  },
  {
    id: "yang",
    char: "阳",
    pinyin: "yáng",
    group: "nature",
    meaning: "阳",
    strokeNames: [],
  },
  {
    id: "hong",
    char: "红",
    pinyin: "hóng",
    group: "nature",
    meaning: "红",
    strokeNames: [],
  },
  {
    id: "huang",
    char: "黄",
    pinyin: "huáng",
    group: "nature",
    meaning: "黄",
    strokeNames: [],
  },
  {
    id: "lan",
    char: "蓝",
    pinyin: "lán",
    group: "nature",
    meaning: "蓝",
    strokeNames: [],
  },
  {
    id: "lv",
    char: "绿",
    pinyin: "lǜ",
    group: "nature",
    meaning: "绿",
    strokeNames: [],
  },
  {
    id: "bai2",
    char: "白",
    pinyin: "bái",
    group: "nature",
    meaning: "白",
    strokeNames: [],
  },
  {
    id: "hei",
    char: "黑",
    pinyin: "hēi",
    group: "nature",
    meaning: "黑",
    strokeNames: [],
  },
  {
    id: "jin2",
    char: "金",
    pinyin: "jīn",
    group: "nature",
    meaning: "金",
    strokeNames: [],
  },
  // —— 动物 ——
  {
    id: "yu2",
    char: "鱼",
    pinyin: "yú",
    group: "animal",
    meaning: "鱼",
    strokeNames: [],
  },
  {
    id: "niao",
    char: "鸟",
    pinyin: "niǎo",
    group: "animal",
    meaning: "鸟",
    strokeNames: [],
  },
  {
    id: "ma3",
    char: "马",
    pinyin: "mǎ",
    group: "animal",
    meaning: "马",
    strokeNames: [],
  },
  {
    id: "niu",
    char: "牛",
    pinyin: "niú",
    group: "animal",
    meaning: "牛",
    strokeNames: [],
  },
  {
    id: "yang2",
    char: "羊",
    pinyin: "yáng",
    group: "animal",
    meaning: "羊",
    strokeNames: [],
  },
  {
    id: "gou",
    char: "狗",
    pinyin: "gǒu",
    group: "animal",
    meaning: "狗",
    strokeNames: [],
  },
  {
    id: "mao",
    char: "猫",
    pinyin: "māo",
    group: "animal",
    meaning: "猫",
    strokeNames: [],
  },
  {
    id: "chong",
    char: "虫",
    pinyin: "chóng",
    group: "animal",
    meaning: "虫",
    strokeNames: [],
  },
  {
    id: "ji2",
    char: "鸡",
    pinyin: "jī",
    group: "animal",
    meaning: "鸡",
    strokeNames: [],
  },
  {
    id: "ya2",
    char: "鸭",
    pinyin: "yā",
    group: "animal",
    meaning: "鸭",
    strokeNames: [],
  },
  {
    id: "zhu",
    char: "猪",
    pinyin: "zhū",
    group: "animal",
    meaning: "猪",
    strokeNames: [],
  },
  {
    id: "tu2",
    char: "兔",
    pinyin: "tù",
    group: "animal",
    meaning: "兔",
    strokeNames: [],
  },
  {
    id: "hu",
    char: "虎",
    pinyin: "hǔ",
    group: "animal",
    meaning: "虎",
    strokeNames: [],
  },
  {
    id: "long",
    char: "龙",
    pinyin: "lóng",
    group: "animal",
    meaning: "龙",
    strokeNames: [],
  },
  {
    id: "she",
    char: "蛇",
    pinyin: "shé",
    group: "animal",
    meaning: "蛇",
    strokeNames: [],
  },
  {
    id: "hou2",
    char: "猴",
    pinyin: "hóu",
    group: "animal",
    meaning: "猴",
    strokeNames: [],
  },
  {
    id: "xiong",
    char: "熊",
    pinyin: "xióng",
    group: "animal",
    meaning: "熊",
    strokeNames: [],
  },
  {
    id: "xiang",
    char: "象",
    pinyin: "xiàng",
    group: "animal",
    meaning: "象",
    strokeNames: [],
  },
  {
    id: "shu3",
    char: "鼠",
    pinyin: "shǔ",
    group: "animal",
    meaning: "鼠",
    strokeNames: [],
  },
  {
    id: "wa",
    char: "蛙",
    pinyin: "wā",
    group: "animal",
    meaning: "蛙",
    strokeNames: [],
  },
];


/** 轻声助词不入库（的/了/着/过/吗/呢/么/们…） */
const LIGHT_TONE_CHARS = new Set(["的", "了", "着", "过", "吗", "呢", "么", "们", "啊", "吧", "嘛", "啦"]);

/**
 * 与 BV1RrySBCEmt《汉语拼音跟我读一读》屏幕韵母表一致的 24 个韵母。
 * 不含 ian/uo/iao/uang 等扩展拼写；字库只保留可用该表拼出的字。
 */
const CHART_FINALS = new Set([
  "a", "o", "e", "i", "u", "v",
  "ai", "ei", "ui", "ao", "ou", "iu", "ie", "ve", "er",
  "an", "en", "in", "un", "vn",
  "ang", "eng", "ing", "ong",
]);

const CHART_INITIALS = [
  "zh", "ch", "sh", "b", "p", "m", "f", "d", "t", "n", "l",
  "g", "k", "h", "j", "q", "x", "r", "z", "c", "s", "y", "w",
];

function stripTonePlain(pinyin) {
  return String(pinyin || "")
    .replace(/[ǖǘǚǜü]/g, "v")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[āáǎà]/g, "a")
    .replace(/[ēéěè]/g, "e")
    .replace(/[īíǐì]/g, "i")
    .replace(/[ōóǒò]/g, "o")
    .replace(/[ūúǔù]/g, "u")
    .toLowerCase()
    .replace(/[^a-z]/g, "");
}

function chartFinalKey(finalPlain, initial) {
  let f = (finalPlain || "").toLowerCase().replace(/ü/g, "v");
  const aliases = { ue: "ve", üe: "ve", ün: "vn", uen: "un", uei: "ui", iou: "iu" };
  f = aliases[f] || f;
  // j/q/x/y 后的 u = ü
  if ((initial === "j" || initial === "q" || initial === "x") && f.startsWith("u") && !f.startsWith("uo")) {
    f = `v${f.slice(1)}`;
  }
  if (initial === "y" && f.startsWith("u") && f !== "ou") {
    f = `v${f.slice(1)}`;
  }
  return f;
}

/** 音节的声母+韵母是否落在视频字表内 */
function isChartSyllable(pinyin) {
  let plain = stripTonePlain(pinyin);
  if (!plain) return false;
  let initial = "";
  for (const ini of CHART_INITIALS) {
    if (plain.startsWith(ini)) {
      initial = ini;
      plain = plain.slice(ini.length) || plain;
      break;
    }
  }
  const finalKey = chartFinalKey(plain, initial);
  if (!CHART_FINALS.has(finalKey)) return false;
  if (initial && !CHART_INITIALS.includes(initial)) return false;
  return true;
}

// 兜底：剔除轻声助词 + 非视频字表组合
export const CHARACTERS = CHARACTERS_RAW.filter(
  (c) => !LIGHT_TONE_CHARS.has(c.char) && isChartSyllable(c.pinyin)
);

export function getCharacter(id) {
  return CHARACTERS.find((c) => c.id === id);
}

export function charactersByGroup(groupId) {
  if (!groupId || groupId === "all") return CHARACTERS;
  return CHARACTERS.filter((c) => c.group === groupId);
}
